# -*- coding: utf-8 -*-
"""Lab2 task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXfqjlTcgt4bvN03Q9x2DMar2nb2Rtdf

**Numpy**
"""



"""**List**"""

my_list = [1, 2, 3, 8, 5,6,7,5,9,10]


print(my_list)
print ('sum:',sum(my_list))
print ('max:',max(my_list))
print ('min:',min(my_list))
my_list.append(33)
print('updated list:',my_list)
my_list.remove(8)
print('updated list:',my_list)
print('ascending',sorted(my_list))
print('descending',sorted(my_list) reverse=true)

min(my_list)

max(my_list)

sum(my_list)

"""***Matplotlib***

**Tuple**
"""

tuple = (1, 2, 3, 4, 5)
print('second element',tuple[1])
print('last element',tuple[-1])
print('first element',tuple[0])
tuple_list=list(tuple)
tuple_list[2]=8
print(tuple_list)



"""**Set**"""

set1 = {1, 2, 3, 4, 5, 5, 4}
set2 = {'a', 'b', 'c', 'c', 'd'}

print("Set 1:", set1)
print("Set 2:", set2)

union_set = set1.union(set2)
print("Union of Set 1 and Set 2:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection of Set 1 and Set 2:", intersection_set)

difference_set1_set2 = set1.difference(set2)
print("Difference (Set 1 - Set 2):", difference_set1_set2)

difference_set2_set1 = set2.difference(set1)
print("Difference (Set 2 - Set 1):", difference_set2_set1)

set1.add(6)
print("Set after adding 6:", set1)
set1.remove(3)
print("Set after removing 3:", set1)

"""**Dictionary**"""

print(my_dict)

# Create a dictionary for student information
student = {
    "name": "Alice",
    "student_id":234,
    "age": 20,
    "major": "Computer Science",
    "gpa": 3.8
}

print("Original dictionary:", student)

student["age"] = 21

print("Updated dictionary:", student)