# -*- coding: utf-8 -*-
"""sk learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hLSFT3gr7AFihJahyjT_ZV18WtyYYN-9
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
data = load_iris()    # Load the Iris dataset
X = data.data         # Features (inputs)
y = data.target       # Labels (outputs)
# Step 2: Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=20
)
# Step 3: Initialize the KNN model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred_test = model.predict(X_test)
# Step 5: Evaluate the model
test_accuracy = accuracy_score(y_test, y_pred_test)
print(f"Test Accuracy: {test_accuracy}")

# Calculate training accuracy
y_pred_train = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_pred_train)
print(f"Train Accuracy: {train_accuracy}")