# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lnk0T5r2s3ix24Skje24W2l2jfXfb7g

Compare the solution paths found by BFS, DFS, and A*.
Which algorithm gives the shortest path? Why?
Which algorithm is more efficient in terms of time and memory?

Compare the solution paths found by BFS, DFS, and A*.

BFS and A* found the shortest path (3 steps).[link text](https://)

DFS found a longer path (7 steps) due to its depth-first nature.

Which algorithm gives the shortest path? Why?

BFS and A* both guarantee the shortest path:

BFS → because it explores in layers (smallest depth first).

A* → because it uses a heuristic to guide the search but still ensures optimality.

Which algorithm is more efficient in terms of time and memory?

DFS is most memory efficient but not reliable (doesn’t guarantee shortest path).

BFS uses a lot of memory and time on large problems.

A* is the best balance: efficient and finds the shortest path quickly, especially if the heuristic is good.
"""

